### ISSUE TITLE
Add README to Dusk organization profile

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/.github#16]
**SUMMARY**
Add a public README to the organization profile

**DESCRIPTION** 
 This file should contain short info on Dusk and quick pointers to useful locations:

For instance, the README could contain:
- A Dusk banner
- Quick intro to Dusk
- A list of the main repos (possibly showing their current status, see the `biaw` example)
- A link to `dusk-index` repo (to be created)
- Other useful pointers (e.g., links to Discord channels, Telegram, etc..)

Nice examples of profile READMEs:
- https://github.com/github
- https://github.com/biaw

**NOTES** 
Note that this README [can have a public and a member version](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-member-only-organization-profile-readme), so we can customize it accordingly.

Please, share your thoughts on what contents you would like to see in this README.
There are countless options to create cool READMEs, so we might want to be creative
See these links for inspiration:
- https://dev.to/github/10-standout-github-profile-readmes-h2o
- https://zzetao.github.io/awesome-github-profile/

**Comment by fed-franz** [comment]
A stub of the profile README can be seen [here](https://github.com/dusk-network/.github/tree/fix-16/profile)

**Comment by HDauven** [comment]
We don't use Reddit anymore in an official capacity, so that one can be removed.

We do use LinkedIn a lot and actively, so my recommendation would be to replace Reddit with Linkedin: https://www.linkedin.com/company/dusknetwork/

**Comment by HDauven** [comment]
Not sure what others think about it, but it might make sense to add these repos as well:

The UI kit one, which will form the basis for a lot of Dusk based dApps:
https://github.com/dusk-network/dusk-ui-kit

The Plonk and Kadcast repos. They're Rust reference implementations by us:
https://github.com/dusk-network/plonk
https://github.com/dusk-network/kadcast

**Comment by fed-franz** [comment]
Resolved by #18
