### ISSUE TITLE
Add member-only GitHub profile page

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/.github#25]
### Summary
 It is possible to have a version of the GitHub profile page just for Dusk's members. This can be useful to point internal resources, such as Onboarding, Dev Guidelines, etc...

### Possible solution design or implementation
Create a private repository called .github-private. Once created, add a /profile/README.md. The README will appear on your organization's profile, visible only to members of the organization. 
Source: [GitHub Docs](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)

**Comment by HDauven** [comment]
Should be finished with this: https://github.com/dusk-network/.github-private/tree/main
